export interface services_carousel{
    id: number;
    img_path: string;
    img_alt: string;
    heading: string;
    details: string;
    button: string;
    link: string;
}

export const ServicesCarousel: services_carousel[] = [
    { id: 1, img_path: "../assets/services_carousel/serv_car1.png", img_alt: "Android", heading: "Android", details: "In the ever-evolving landscape of Android app development, achieving excellence is the goal. We specialize in crafting Android applications that not only amplify your digital presence but also captivate and enthrall your audience. Our dedicated team of Android aficionados ensures your app isn't just utilitarian, but also a visual masterpiece, user-friendly, and impeccably optimized for the Android ecosystem. From conceptualization to final production, we stand as your stalwart allies, guiding you through every phase of your app's journey.", button: "More", link: "" },
    { id: 2, img_path: "../assets/services_carousel/serv_car2.png", img_alt: "iOS", heading: "iOS", details: "In the realm of iOS, nothing short of excellence suffices. Our iOS app development services are meticulously tailored to surpass the exacting standards set by Apple's discerning user base. Whether your app is destined for iPhone, iPad, or Apple Watch, we meticulously ensure it embodies Apple's unwavering commitment to quality, design, and unparalleled user experiences.", button: "More", link: "" },
    { id: 3, img_path: "../assets/services_carousel/serv_car3.png", img_alt: "flutter", heading: "Flutter", details: "In a world where cross-platform development is no longer an option but a necessity, Flutter emerges as the game-changer. We harness the power of this revolutionary framework to deliver stunning, consistent, and high-performing mobile apps that seamlessly span both Android and iOS platforms, all from a single codebase.", button: "More", link: "" },
    { id: 4, img_path: "../assets/services_carousel/serv_car4.png", img_alt: "language", heading: "Language Technology Solutions Language Identification", details: "Language identification is used to identify languages spoken in audio when compared against a list of supported languages. AI translation is a machine translation process based on complex deep learning algorithms. Using intelligent behaviour, it can reason and understand a source text and generate another in a different language.", button: "More", link: "" },
    { id: 5, img_path: "../assets/services_carousel/serv_car5.png", img_alt: "software_dev", heading: "Software & App Development", details: "We are at the forefront of innovative software and app development. Our commitment to innovation and excellence allows us to deliver tailored solutions that meet the unique needs of businesses across industries.", button: "More", link: "" },
    { id: 6, img_path: "../assets/services_carousel/serv_car6.png", img_alt: "mobile_app", heading: "Mobile App Development", details: "We specialize in mobile app development that not only elevates your digital presence but also reaches a broader audience. Our team of experts is dedicated to creating apps that are not just functional but also visually striking, user-friendly, and optimized for both Android and iOS ecosystems, utilizing Flutter for both platforms. From concept to prototype and from prototype to production-ready app, we are your partners in every step of the journey.", button: "More", link: "" },
    { id: 7, img_path: "../assets/services_carousel/serv_car7.png", img_alt: "web_dev", heading: "Website Development", details: "We specialize in crafting dynamic and user-centric websites and portals that drive digital success. Our team of skilled developers and designers leverages the latest technologies and best practices to create online solutions tailored to your business needs.", button: "More", link: "" },
    { id: 8, img_path: "../assets/services_carousel/serv_car8.png", img_alt: "data_science", heading: "Data Science", details: "In the era of data-driven decision-making, harnessing the power of data is essential for staying ahead in today's competitive landscape. we specialize in Data Science solutions that transform raw data into actionable insights, empowering your business to make informed decisions, optimize operations, and achieve remarkable growth.", button: "More", link: "" },
    { id: 9, img_path: "../assets/services_carousel/serv_car9.png", img_alt: "ui_ux", heading: "UI/UX Design", details: "In the digital era, the user experience is paramount. We specialize in crafting extraordinary user interfaces (UI) and user experiences (UX) that transcend the ordinary. Our mission is to create digital journeys that are not just functional but delightful, engaging, and unforgettable.", button: "More", link: "" },
    { id: 10, img_path: "../assets/services_carousel/serv_car10.png", img_alt: "quality_assurance", heading: "Quality Assurance", details: "We understand that quality is the cornerstone of any successful project. Our dedicated Quality Assurance (QA) team is committed to ensuring that your products and services meet the highest standards of excellence. With rigorous testing, meticulous attention to detail, and a customer-centric approach, we are your trusted partner in delivering quality-driven solutions.", button: "More", link: "" },
    { id: 11, img_path: "../assets/services_carousel/serv_car11.png", img_alt: "pro_manage", heading: "Project Management", details: "Effective project management is the cornerstone of success in today's dynamic business landscape.we are your partners in achieving project excellence. Our project management expertise, honed through years of experience, empowers organizations to navigate complexities, meet deadlines, and deliver results that exceed expectations.", button: "More", link: "" },
    { id: 12, img_path: "../assets/services_carousel/serv_car12.png", img_alt: "devOps", heading: "DevOps", details: "In the digital era, the user experience is paramount. We specialize in crafting extraordinary user interfaces (UI) and user experiences (UX) that transcend the ordinary. Our mission is to create digital journeys that are not just functional but delightful, engaging, and unforgettable.", button: "More", link: "" },
    { id: 13, img_path: "../assets/services_carousel/serv_car13.png", img_alt: "tech_support", heading: "Technical Support", details: "We redefine technical support as more than just problem-solving. We view it as a strategic partnership that ensures your technology backbone remains robust, dependable, and an enabler of your business goals. Our dedicated technical support team stands ready to provide you with the unwavering assistance you need to thrive in the digital landscape.", button: "More", link: "" },
    { id: 14, img_path: "../assets/services_carousel/serv_car14.png", img_alt: "IT_infra", heading: "IT Infrastructure", details: "We recognize that a solid IT infrastructure forms the backbone of any modern business. Our comprehensive IT infrastructure services are designed to build, optimize, and maintain a resilient technology foundation that ensures your operations run seamlessly, securely, and efficiently.", button: "More", link: "" },
    { id: 15, img_path: "../assets/services_carousel/serv_car15.png", img_alt: "ai_ml", heading: "AI/ML", details: "In the age of data-driven transformation, Artificial Intelligence (AI) and Machine Learning (ML) are not just buzzwords; they're the driving force behind innovation. We are trailblazers in the AI and ML realm, shaping industries with groundbreaking solutions that redefine possibilities.", button: "More" , link: ""}
]